# Generated by Django 5.1.1 on 2024-10-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Amaterno',
            field=models.CharField(default='perez', max_length=50, verbose_name='Apellido Materno'),
            preserve_default=False,
        ),
    ]
